ALA_BB : ALA_SC1
ALA_SC1 : ALA_BB
ARG_BB : ARG_SC1
ARG_SC1 : ARG_BB  ARG_SC2
ARG_SC2 : ARG_SC1
ASN_BB : ASN_SC1
ASN_SC1 : ASN_BB
ASP_BB : ASP_SC1
ASP_SC1 : ASP_BB
CYS_BB : CYS_SC1
CYS_SC1 : CYS_BB
CYX_BB : CYX_SC1
### Will bond to next bead other than itself ###
CYX_SC1 : CYX_BB  CYX_SC1
################################################
GLN_BB : GLN_SC1
GLN_SC1 : GLN_BB
GLU_BB : GLU_SC1
GLU_SC1 : GLU_BB
###      Fixed     ###
GLY_BB : Skip
######################
HID_BB : HID_SC1
HID_SC1 : HID_BB HID_SC2 HID_SC3
HID_SC2 : HID_SC1 HID_SC3
HID_SC3 : HID_SC1 HID_SC2
HIE_BB : HIE_SC1
HIE_SC1 : HIE_BB HIE_SC2 HIE_SC3
HIE_SC2 : HIE_SC1 HIE_SC3
HIE_SC3 : HIE_SC1 HIE_SC2
HIS_BB : HIS_SC1
HIS_SC1 : HIS_BB HIS_SC2 HIS_SC3
HIS_SC2 : HIS_SC1 HIS_SC3
HIS_SC3 : HIS_SC1 HIS_SC2
ILE_BB : ILE_SC1
ILE_SC1 : ILE_BB
LEU_BB : LEU_SC1
LEU_SC1 : LEU_BB
LYS_BB : LYS_SC1
LYS_SC1 : LYS_BB LYS_SC2
LYS_SC2 : LYS_SC1
MET_BB : MET_SC1
MET_SC1 : MET_BB
PHE_BB : PHE_SC1 
PHE_SC1 : PHE_BB PHE_SC2 
PHE_SC2 : PHE_SC1 PHE_SC3
PHE_SC3 : PHE_SC2 
PRO_BB : PRO_SC1
PRO_SC1 : PRO_BB
SER_BB : SER_SC1
SER_SC1 : SER_BB
THR_BB : THR_SC1
THR_SC1 : THR_BB
TRP_BB : TRP_SC1
TRP_SC1 : TRP_BB  TRP_SC2  TRP_SC3
TRP_SC2 : TRP_SC1 TRP_SC3
TRP_SC3 : TRP_SC1  TRP_SC2  TRP_SC4  TRP_SC5
TRP_SC4 : TRP_SC3 TRP_SC5
TRP_SC5 : TRP_SC3 TRP_SC4
TYR_BB : TYR_SC1 
TYR_SC1 : TYR_BB  TYR_SC2  TYR_SC3
TYR_SC2 : TYR_SC1  TYR_SC4
TYR_SC3 : TYR_SC1  TYR_SC4
TYR_SC4 : TYR_SC2  TYR_SC3
VAL_BB : VAL_SC1
VAL_SC1 : VAL_BB
### POPC Bonds ###
PC_NC3 : PC_PO4
PC_PO4 : PC_NC3
PC_PO4 : PC_GL1
PC_GL1 : PC_PO4
PC_PO4 : PC_GL2
PC_GL2 : PC_PO4
PC_GL2 : PA_C1B
PA_C1B : PC_GL2
PC_GL1 : OL_C1A
OL_C1A : PC_GL1 
PA_C1B : PA_C2B   
PA_C2B : PA_C1B
PA_C2B : PA_C3B   
PA_C3B : PA_C2B
PA_C3B : PA_C4B 
PA_C4B : PA_C3B
OL_C1A : OL_D2A 
OL_D2A : OL_C1A
OL_D2A : OL_C3A 
OL_C3A : OL_D2A
OL_C3A : OL_C4A 
OL_C4A : OL_C3A

