ACE_RE : 0
SER_BB : 0
SER_SC1 : 0
VAL_BB : 0
VAL_SC1 : 0
TYR_BB : 0
TYR_SC1 : 0
TYR_SC2 : 0
TYR_SC4 : 0
TYR_SC3 : 0
ILE_BB : 0
ILE_SC1 : 0
THR_BB : 0
THR_SC1 : 0
GLU_BB : 0
GLU_SC1 : -1
LEU_BB : 0
LEU_SC1 : 0
ALA_BB : 0
ALA_SC1 : 0
GLY_BB : 0
ASN_BB : 0
ASN_SC1 : 0
CYS_BB : 0
CYS_SC1 : 0
TRP_BB : 0
TRP_SC1 : 0
TRP_SC2 : 0
TRP_SC3 : 0
TRP_SC5 : 0
TRP_SC4 : 0
GLN_BB : 0
GLN_SC1 : 0
PHE_BB : 0
PHE_SC1 : 0
PHE_SC2 : 0
PHE_SC3 : 0
ASP_BB : 0
ASP_SC1 : -1
PRO_BB : 0
PRO_SC1 : 0
CYX_BB : 0
CYX_SC1 : 0
HIE_BB : 0
HIE_SC1 : 0
HIE_SC3 : 0
HIE_SC2 : 0
ARG_BB : 0
ARG_SC1 : 0
ARG_SC2 : 1
LYS_BB : 0
LYS_SC1 : 0
LYS_SC2 : 1
MET_BB : 0
MET_SC1 : 0
HID_BB : 0
HID_SC1 : 0
HID_SC3 : 0
HID_SC2 : 0
NME_RE : 0
