TYR_BB : 0
TYR_SC1 : 0
TYR_SC2 : 0
TYR_SC4 : 0
TYR_SC3 : 0
ASP_BB : 0
ASP_SC1 : -1
PRO_BB : 0
PRO_SC1 : 0
GLU_BB : 0
GLU_SC1 : -1
THR_BB : 0
THR_SC1 : 0
GLY_BB : 0
TRP_BB : 0
TRP_SC1 : 0
TRP_SC2 : 0
TRP_SC3 : 0
TRP_SC5 : 0
TRP_SC4 : 0
